### PR TITLE
lts: pre-commit-nix

### PR DESCRIPTION
**Pull request by khuzema786**

### CODE REVIEW

**Review by srid — CHANGES_REQUESTED** [review]
You should test your changes. This change does not even build.

```
❯ nix run github:srid/nixci
🍏 .
🐚 nix --extra-experimental-features 'nix-command flakes' eval '.#nixci.default' --json
Error: Command error: Process exited unsuccessfully. exit_code=Some(1) stderr=warning: Git tree '/home/srid/code/ny/location-tracking-service' is dirty
error:
       … while evaluating the attribute 'optionalValue.value'

         at /nix/store/3i5iasvc4035gna928p7iwnmv8nify1k-source/lib/modules.nix:806:5:

          805|
          806|     optionalValue =
             |     ^
          807|       if isDefined then { value = mergedValue; }

       … while evaluating a branch condition

         at /nix/store/3i5iasvc4035gna928p7iwnmv8nify1k-source/lib/modules.nix:807:7:

          806|     optionalValue =
          807|       if isDefined then { value = mergedValue; }
             |       ^
          808|       else {};

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: The option `perSystem.x86_64-linux.pre-commit' does not exist. Definition values:
       - In `/nix/store/09538anlr7ydawb1fgw7zfx1bv8r8d2m-source/flake.nix, via option perSystem':
           {
             settings = {
               hooks = {
                 clippy = {
                   enable = true;
           ...
```

You are missing the flake-part module,

1.  Add the input, https://github.com/nammayatri/common/blob/ac4b0421da7088877deba240e0b19bf1f8616a86/flake.nix#L18
2. `import` it, https://github.com/nammayatri/common/blob/ac4b0421da7088877deba240e0b19bf1f8616a86/flake-module.nix#L12
3. enable it, https://github.com/nammayatri/common/blob/ac4b0421da7088877deba240e0b19bf1f8616a86/nix/pre-commit.nix#L8
4. ... and of course test it locally.

**Comment by khuzema786** [comment]
@srid Thanks for the guidance. I am doing the above changes and will update this PR if health check passes.

**Comment by srid** [comment]
@khuzema786 You should improve the upstream flake-module as well:

https://github.com/nammayatri/common/blob/ac4b0421da7088877deba240e0b19bf1f8616a86/flake-module.nix#L17

That's what makes `perSystem.*.pre-commit` option set available.

**Comment by srid** [comment]
I've got the CI build to work, but the local clippy run will fail because pre-commit-hooks-nix is using a different Rust compiler version. I will need to fix this properly.

**Comment by srid** [comment]
Pushed a small fix for now. @khuzema786 Take a look at this PR and see if it works for you. See README.md

**Comment by khuzema786** [comment]
@srid yes now I was able to do nix run successfully. Is it good to get merged to main ? Also jenkins build seems to get stuck.

**Review by srid — APPROVED** [review]
Talk to Hemanth about Jenkins. 

If `nixci` succeeds locally, you can merge this PR.

**Pull request merged**
